name: publish-on-push

on: [push]

permissions:
  contents: write

jobs:
  ci:
    name: Build and publish package
    runs-on: ubuntu-latest
    steps:
        - name: Check out source code
          uses: actions/checkout@v4

        - name: Enable Corepack
          run: corepack enable

        - name: Use Node.js 💻
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: yarn

        - name: Install dependencies
          run: yarn install --immutable

        - name: Build
          run: yarn build

        - name: Publish package
          run: yarn pkg-pr-new publish

  pages:
    name: Build and deploy docs to GitHub Pages
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'
    steps:
        - name: Check out source code
          uses: actions/checkout@v4

        - name: Enable Corepack
          run: corepack enable

        - name: Use Node.js 💻
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: yarn

        - name: Install dependencies
          run: yarn install --immutable

        - name: Build docs
          run: yarn docs

        - name: Build examples
          run: yarn vite build -c vite.examples.config.js

        - name: Deploy docs
          uses: peaceiris/actions-gh-pages@v4
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs